### ISSUE TITLE
Feature request: Report capacity 0 instead of panick when alignment isn't satisfied

### ISSUE THREAD

**Issue by juchiast** [bodil/sized-chunks#22]
Currently, it is not possible to use `im` to store i64, f64, etc. on architectures where `usize` alignment is less than 8, such as WASM and arm32 (https://github.com/bodil/im-rs/issues/174).

I think `InlineArray` should report capacity 0 instead of panicking to support more architectures.

**Comment by kornelski** [comment]
You can use the backing storage type `T` to get bigger alignment, i.e. instead of storing `i64` in `[u8; 8]`, you can store it in `[i64; 1]`.

**Comment by juchiast** [comment]
Thanks! I uses this indirectly through `im`, so I don't have much control to get around the issue.

**Comment by juchiast** [comment]
I could use `#[repr(packed)]` on my struct to reduce the alignment, but unfortunately it also needs `#[derive(Deserialize)]`, and it is not possible to derive on packed and `!Copy` types at the moment.

**Comment by bodil** [comment]
Almost sounds to me like it's worth making the `InlineArray` itself align 8, to lessen the risk of misalignment.
