### ISSUE TITLE
Version 0.3.2 is marked as compatible with Version 0.3.0, but introduces dependency on later rustc version

### ISSUE THREAD

**Issue by dwightguth** [bodil/sized-chunks#4]
im-rc version 13.0.0 depends on sized-chunks ^0.3.0. However, this means that with the release of sized-chunks 0.3.2, im-rc 13.0.0 does not build with rustc 1.34 anymore because this version of this dependency introduces a dependency on a rust feature that is unstable in that release. It would be better if breaking changes to a package were not included in a point release.

**Comment by bodil** [comment]
Agreed, I'm going to deprecate this release and retag it as a major bump.

(It's not a point release, though, it's still on 0.x so this was a minor bump, but the problem remains.)

**Comment by bodil** [comment]
Tagged and published: https://github.com/bodil/sized-chunks/releases/tag/v0.4.0
