### ISSUE TITLE
SIGSEGV with cargo test --release

### ISSUE THREAD

**Issue by cuviper** [bodil/sized-chunks#7]
Starting in 0.5.2, I found that `cargo test --release` hits a segmentation fault within `tests::inline_array::test_actions`.

This seems to be a direct consequence of 93db48b9a889160651b3e45d64bac450f32e9a66, as the proptests appear to exercise a few conditions that are expected to panic (and be caught). But now that those checks are only kept in debug mode, this **safe** code is able to trigger memory unsafety.

**Comment by cuviper** [comment]
To be fair, you did say this in the changelog too:

> - Internal consistency assertions are now only performed in debug mode (like with `debug_assert!`). This means `sized_chunks` will no longer cause panics in release mode when you do things like pushing to a full chunk, but do bad and undefined things instead. It also means a very slight performance gain.

But I would argue that this is very un-Rust-like, especially for only a very slight gain.

**Comment by cuviper** [comment]
A more idiomatic approach would be to split the API into unsafe-unchecked versions for those that can be **sure** of their correct use, e.g.

```rust
    pub fn push(&mut self, value: A) {
        if self.is_full() {
            panic!("InlineArray::push: chunk size overflow");
        }
        unsafe { self.push_unchecked(value) }
    }

    pub unsafe fn push_unchecked(&mut self, value: A) {
        self.write_at(self.len(), value);
        *self.len_mut() += 1;
    }
```

**Comment by bodil** [comment]
Ugh, that commit wasn't supposed to be in the release, it was just for performance testing and the benchmarks didn't justify it. I'm going to revert it and push a new release.

**Comment by bodil** [comment]
New release tagged with this commit reverted, and I yanked the offending version just for good measure.

**Comment by cuviper** [comment]
Thanks for the quick fix!

**Comment by bodil** [comment]
Thanks for the quick spot.  😊
